name: Lint Profile Navigation

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint-profile-nav:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run profile navigation lint
        run: node scripts/lint-profile-nav.mjs
